server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ewm_main
    username: postgres_main
    password: postgres
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

stats-server:
  url: http://localhost:9090

logging:
  level:
    root: INFO
    ru.yandex.practicum: DEBUG