server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ewm_main
    username: postgres_main
    password: postgres
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

stats-server:
  url: http://localhost:9090

logging:
  level:
    org:
      springframework:
        orm:
          jpa: INFO
        web: DEBUG
        transaction: INFO
        transaction.interceptor: TRACE
        orm.jpa.JpaTransactionManager: DEBUG
      slf4j: INFO
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBined: TRACE
    ru.practicum: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
    org.springframework.cloud.client.discovery: DEBUG