spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations:
            - classpath:config/core/{application}
            - classpath:config/stats/{application}
            - classpath:config/infra/{application}

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://discovery-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
    enabled: true
  instance:
    preferIpAddress: true
    hostname: config-server