server:
  port: 9090

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${STATS_DB_HOST:localhost}:${STATS_DB_PORT:6543}/${STATS_DB_NAME:ewm_stats}
    username: ${STATS_DB_USERNAME:postgres_stats}
    password: ${STATS_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE