services:
  stats-db:
    image: postgres:16.1
    container_name: postgres-ewm-stats-db
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: postgres_stats
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ewm_stats
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-db:
    image: postgres:16.1
    container_name: postgres-ewm-main-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres_main
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ewm_main
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      timeout: 5s
      interval: 5s
      retries: 10