server:
  port: 0

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${EVENT_DB_HOST:localhost}:${EVENT_DB_PORT:6545}/${EVENT_DB_NAME:event}
    username: ${EVENT_DB_USERNAME:event}
    password: ${EVENT_DB_PASSWORD:event}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

hibernate:
  jdbc:
    time_zone: UTC

logbook:
  format:
    style: http

stats-server:
  name: stats-server

logging:
  level:
    org.springframework.web: INFO
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.springframework.transaction.interceptor: INFO
    org.springframework.orm.jpa.JpaTransactionManager: INFO
    org.zalando.logbook: TRACE