server:
  port: 0

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6545/event
    username: event
    password: event
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

hibernate:
  jdbc:
    time_zone: UTC

logbook:
  format:
    style: http

stats-server:
  name: stats-server

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.web.reactive: DEBUG

    org.springframework.cloud.openfeign: DEBUG
    feign: DEBUG
    com.netflix: DEBUG

    ru.yandex.practicum: DEBUG

    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG

    com.netflix.discovery: DEBUG
    com.netflix.eureka: DEBUG

    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG